export type CatalogModule='overview'|'stats'|'status'|'assets'|'carriers'|'activity'|'research'|'live-spores'|'timeline'|'spores'|'transfers'|'transaction-gallery'|'wallet-gallery'|'social-media'|'contracts'|'objects'|'collections'|'catalogs'|'propagations'|'discoveries'|'routes'|'health/scarce'|'propagators'|'scouts'|'graph'|'wallet';
export type CatalogParam='limit'|'offset'|'q'|'status'|'target'|'range'|'root'|'depth'|'nodes'|'type'|'health'|'address';
export interface CatalogRequest {module:CatalogModule;id?:string;params?:Partial<Record<CatalogParam,string|number>>;live?:boolean}
export interface ObserverContext {networkId?:string;role?:'OBSERVER';[key:string]:unknown}
export interface CatalogEnvelope {[key:string]:unknown;__observer?:ObserverContext}
export interface CatalogPage<T=CatalogEnvelope> extends CatalogEnvelope {items:T[];total?:number;limit?:number;offset?:number}
export interface ObserverHealth {status:'ok';networkId:string;workers:Record<string,unknown>}
export interface ObserverClientOptions {url?:string;fetch?:typeof fetch;timeoutMs?:number;socketFactory?:(url:string,options:Record<string,unknown>)=>any}
export interface RequestOptions {signal?:AbortSignal}
export interface LiveUpdate<T=unknown> {kind:'snapshot'|'patch';revision:number}
export interface LiveSubscription {readonly key:string;close():void}
export interface CommunityObserverOptions {home:string;network?:string;port?:number;initializePublicNetwork?:boolean;config?:Record<string,unknown>;policy?:unknown;multi?:unknown;engine?:{createCommunityObserver(options:Record<string,unknown>):Promise<CommunityObserver>}}
export interface CommunityObserver {readonly networkId:string;readonly url:string;status():Record<string,unknown>;catalog(request:CatalogRequest):unknown;submit(candidate:unknown):boolean;close():Promise<void>}
export declare const OBSERVER_MODULES:readonly CatalogModule[];
export declare const OBSERVER_CATALOG:Readonly<Record<CatalogModule,{readonly module:CatalogModule;readonly transport:'catalog';readonly live:boolean}>>;
export declare class MyriaObserverError extends Error {readonly code:string;readonly status?:number;constructor(code:string,message?:string,options?:{status?:number;cause?:unknown})}
export declare class MyriaObserverClient {
 constructor(options?:ObserverClientOptions);readonly url:string;
 health(options?:RequestOptions):Promise<ObserverHealth>;catalog<T=CatalogEnvelope>(request:CatalogRequest,options?:RequestOptions):Promise<T>;
 discoveryCapsule(request:{type:'CATALOG'|'COLLECTION';id:string;signal?:AbortSignal}):Promise<{capsule:string}>;socialMediaImageUrl(postId:string):string;
 overview<T=CatalogEnvelope>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;stats<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;status<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;assets<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;carriers<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;activity<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;research<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;liveSpores<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;timeline<T=CatalogEnvelope>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 spores<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;spore<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;transfers<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;transactionGallery<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;walletGallery<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;socialMedia<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 contracts<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;contract<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;objects<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;object<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;collections<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;collection<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;catalogs<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;catalogDetail<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 propagations<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;propagation<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;discoveries<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;discovery<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;routes<T=CatalogPage>(target:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scarce<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 keepers<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;keeper<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scouts<T=CatalogPage>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scout<T=CatalogEnvelope>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;graph<T=CatalogEnvelope>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;wallet<T=CatalogEnvelope>(address:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 subscribe<T=unknown>(request:CatalogRequest,listener:(value:T,update:LiveUpdate<T>)=>void,options?:{onError?:(error:MyriaObserverError)=>void}):LiveSubscription;close():void;
}
export declare function createMyriaObserverClient(options?:ObserverClientOptions):MyriaObserverClient;
export declare function createCommunityObserver(options:CommunityObserverOptions):Promise<CommunityObserver>;
export * from './storage.js';
