export type HexId=string;
export type AtomicUnits=string;
export type TimestampMs=number;
export type CatalogModule='overview'|'stats'|'status'|'assets'|'carriers'|'activity'|'research'|'live-spores'|'timeline'|'spores'|'transfers'|'transaction-gallery'|'wallet-gallery'|'social-media'|'contracts'|'objects'|'collections'|'catalogs'|'propagations'|'discoveries'|'routes'|'health/scarce'|'propagators'|'scouts'|'graph'|'wallet';
export type CatalogParam='limit'|'offset'|'q'|'status'|'target'|'range'|'root'|'depth'|'nodes'|'type'|'health'|'address';
export interface CatalogRequest {module:CatalogModule;id?:string;params?:Partial<Record<CatalogParam,string|number>>;live?:boolean}
export interface FeeQuote {operation:'TRANSFER'|'TOKEN_CREATE'|'CONTRACT_DEPLOY'|'CONTRACT_EXEC';workUnits:string;estimatedFeeUnits:AtomicUnits;maximumFeeUnits:AtomicUnits}
export interface FeeMarketSnapshot {profile:string;scheduleId:HexId;source:'VERIFIED_SETTLEMENTS'|'CERTIFIED_KEEPER_OFFERS'|'GENESIS_BOOTSTRAP';samples:number;certifiedOffers:number;assetDecimals:number;bootstrapAtomsPerWorkUnit:AtomicUnits;p25:AtomicUnits;median:AtomicUnits;p75:AtomicUnits;p90:AtomicUnits;recommendedAtomsPerWorkUnit:AtomicUnits;maximumAtomsPerWorkUnit:AtomicUnits;quotes:FeeQuote[]}
export interface ObserverContext {networkId?:HexId;role?:'OBSERVER';workers?:Record<string,unknown>;sources?:Record<string,unknown>;budgets?:Record<string,unknown>;feeMarket?:FeeMarketSnapshot|null;[key:string]:unknown}
export interface CatalogEnvelope {[key:string]:unknown;__observer?:ObserverContext}
export interface CatalogPage<T=ObservedRecord> extends CatalogEnvelope {items:T[];total?:number;limit?:number;offset?:number}
export interface ObserverHealth {status:'ok';networkId:HexId;workers:Record<string,unknown>}
export interface ObserverStatus extends CatalogEnvelope {role:'OBSERVER';startedAt:number;uptimeMs:number;queue:number;verify:boolean;activeChecks:boolean;workers:Record<string,{state:string;queued?:number}>;sources:Record<string,unknown>;announcements:Record<string,number>;storage:Record<string,unknown>;budgets:Record<string,number>;feeMarket:FeeMarketSnapshot|null}
export interface ObserverOverview extends CatalogEnvelope {stats:Record<string,number|string|boolean|null>;status:ObserverStatus;carriers:CarrierSummary[];activity:ActivityEvent[];discoveries:unknown[];discoveryCursor?:string|number;timeline:unknown}
export interface ObservedRecord {[key:string]:unknown;id:string;type:string;status:string;firstObservedAt:TimestampMs;lastObservedAt:TimestampMs;lastVerifiedAt:TimestampMs;objectId?:HexId;manifestId?:HexId;healthStatus?:'CRITICAL'|'SCARCE'|'UNDER_REPLICATED'|'HEALTHY'|'UNKNOWN';data:Record<string,unknown>;sources?:unknown[]}
export interface RouteRecord {[key:string]:unknown;routeId:string;targetType:string;targetId:string;locator?:string;carrierClass:string;verificationStatus:string;firstObservedAt:TimestampMs;lastObservedAt:TimestampMs;lastVerifiedAt:TimestampMs}
export interface CarrierSummary {[key:string]:unknown;carrierClass?:string;status?:string;routes?:number}
export interface ActivityEvent {[key:string]:unknown;id:string|number;timestamp:TimestampMs;eventType:string;targetType:string;targetId:string}
export interface Recoverability {[key:string]:unknown;healthStatus:'CRITICAL'|'SCARCE'|'UNDER_REPLICATED'|'HEALTHY'|'UNKNOWN';completeCopies?:number;independentOrigins?:number;carrierClasses?:number}
export interface RecordDetail extends ObservedRecord,CatalogEnvelope {transaction?:Record<string,unknown>;recentSpores?:RouteRecord[];routes?:CatalogPage<RouteRecord>|RouteRecord[];health?:Recoverability;contents?:CatalogPage<DirectoryEntry>;importReady?:boolean}
export interface DirectoryEntry {[key:string]:unknown;path:string;type?:string;targetId?:string;size?:number;hash?:string}
export interface AssetRecord {[key:string]:unknown;assetId:HexId;name?:string;symbol?:string;decimals:number;issuer?:string;supplyPolicy:string;fixedSupply?:AtomicUnits;observedSupply?:AtomicUnits;holders?:number;transfers?:number;status:string;firstObservedAt:TimestampMs;lastObservedAt:TimestampMs;lastVerifiedAt:TimestampMs}
export interface AssetCatalog extends CatalogEnvelope {networkId:HexId;scope:'LOCAL_ACCEPTED_LEDGER';available:boolean;items:AssetRecord[];total?:number}
export interface ObservedBalance {[key:string]:unknown;balance:AtomicUnits|null;received?:AtomicUnits;spent?:AtomicUnits;conflicts?:number;status?:string}
export interface WalletTokenBalance {[key:string]:unknown;assetId:HexId;name?:string;symbol?:string;decimals:number;units:AtomicUnits;display?:string}
export interface WalletDetail extends CatalogEnvelope {[key:string]:unknown;address:string;found:boolean;balance:ObservedBalance;tokens:WalletTokenBalance[];items?:unknown[];total?:number;limit?:number;offset?:number}
export interface TransferRecord extends ObservedRecord {data:{operation?:string;from?:string;to?:string;assetId?:HexId;amount?:AtomicUnits;fee?:AtomicUnits;[key:string]:unknown}}
export interface WasmFragmentSummary {observed:number;verified:number;expected:number|null;complete:boolean;codeBytes:number}
export interface ContractSource {javascript:string;sourceHash:HexId;buildProfile:string;compiler:string;scope:string;verification:string;collectionId?:HexId;headId?:HexId;sourceUrl?:string;retrievedAt?:TimestampMs}
export interface ContractExecution {transactionId:HexId;invocationId?:HexId;executionId?:HexId;sender?:string;input?:unknown;status:string;reason?:string|null;output?:unknown;rewards:Array<{to:string;amountUnits:AtomicUnits}>;observedAt:TimestampMs;verifiedAt:TimestampMs}
export interface ContractDetail extends ObservedRecord,CatalogEnvelope {name?:string;deploymentObjectId:HexId;lastActivityAt:TimestampMs;executionTotal:number;wasmFragments:WasmFragmentSummary;source:ContractSource|null;runtime:Record<string,unknown>|null;rewardHistory:{availableUnits:AtomicUnits;withdrawnUnits:AtomicUnits;transferredUnits:AtomicUnits};executions:ContractExecution[];executionLimit:number}
export interface ParticipantDetail extends CatalogEnvelope {[key:string]:unknown;id:string;type:'KEEPER'|'SCOUT';status:string;publisher:string;firstObservedAt:TimestampMs;lastObservedAt:TimestampMs;lastVerifiedAt:TimestampMs;claims:ObservedRecord[];claimTotal:number;claimLimit:number;rewardDestinations?:string[];signerFingerprints?:string[];keeperDirectories?:unknown[];scope:'OBSERVED_ID_NOT_UNIQUE_HUMAN'}
export interface GraphNode {[key:string]:unknown;id:string;type:string;label?:string;status?:string;observedAt?:TimestampMs}
export interface GraphEdge {[key:string]:unknown;source:string;target:string;type:string}
export interface GraphResult extends CatalogEnvelope {nodes:GraphNode[];edges:GraphEdge[];[key:string]:unknown}
export interface ObserverClientOptions {url?:string;fetch?:typeof fetch;timeoutMs?:number;socketFactory?:(url:string,options:Record<string,unknown>)=>any}
export interface RequestOptions {signal?:AbortSignal}
export interface LiveUpdate<T=unknown> {kind:'snapshot'|'patch';revision:number}
export interface LiveSubscription {readonly key:string;close():void}
export interface ObserverEngineAdapter {createCommunityObserver(options:Record<string,unknown>):Promise<CommunityObserver>}
export interface CommunityObserverOptions {home:string;engine:ObserverEngineAdapter;network?:string;port?:number;initializePublicNetwork?:boolean;config?:Record<string,unknown>;policy?:unknown;multi?:unknown}
export interface CommunityObserver {readonly networkId:string;readonly url:string;status():Record<string,unknown>;catalog(request:CatalogRequest):unknown;submit(candidate:unknown):boolean;close():Promise<void>}
export declare const OBSERVER_MODULES:readonly CatalogModule[];
export declare const OBSERVER_CATALOG:Readonly<Record<CatalogModule,{readonly module:CatalogModule;readonly transport:'catalog';readonly live:boolean}>>;
export declare class MyriaObserverError extends Error {readonly code:string;readonly status?:number;constructor(code:string,message?:string,options?:{status?:number;cause?:unknown})}
export declare class MyriaObserverClient {
 constructor(options?:ObserverClientOptions);readonly url:string;
 health(options?:RequestOptions):Promise<ObserverHealth>;catalog<T=CatalogEnvelope>(request:CatalogRequest,options?:RequestOptions):Promise<T>;
 discoveryCapsule(request:{type:'CATALOG'|'COLLECTION';id:HexId;signal?:AbortSignal}):Promise<{capsule:string}>;socialMediaImageUrl(postId:string):string;
 overview<T=ObserverOverview>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;stats<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;status<T=ObserverStatus>(options?:RequestOptions):Promise<T>;assets<T=AssetCatalog>(options?:RequestOptions):Promise<T>;carriers<T=CatalogEnvelope&{items:CarrierSummary[]}>(options?:RequestOptions):Promise<T>;activity<T=CatalogPage<ActivityEvent>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;research<T=CatalogEnvelope>(options?:RequestOptions):Promise<T>;liveSpores<T=CatalogEnvelope>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;timeline<T=CatalogEnvelope>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 spores<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;spore<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;transfers<T=CatalogPage<TransferRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;transactionGallery<T=CatalogPage<TransferRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;walletGallery<T=CatalogPage<WalletDetail>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;socialMedia<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 contracts<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;contract<T=ContractDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;objects<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;object<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;collections<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;collection<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;catalogs<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;catalogDetail<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 propagations<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;propagation<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;discoveries<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;discovery<T=RecordDetail>(id:HexId,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;routes<T=CatalogPage<RouteRecord>>(target:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scarce<T=CatalogPage<ObservedRecord&Recoverability>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 keepers<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;keeper<T=ParticipantDetail>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scouts<T=CatalogPage<ObservedRecord>>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;scout<T=ParticipantDetail>(id:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;graph<T=GraphResult>(params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;wallet<T=WalletDetail>(address:string,params?:Record<string,string|number>,options?:RequestOptions):Promise<T>;
 subscribe<T=unknown>(request:CatalogRequest,listener:(value:T,update:LiveUpdate<T>)=>void,options?:{onError?:(error:MyriaObserverError)=>void}):LiveSubscription;close():void;
}
export declare function createMyriaObserverClient(options?:ObserverClientOptions):MyriaObserverClient;
export declare function createCommunityObserver(options:CommunityObserverOptions):Promise<CommunityObserver>;
export * from './storage.js';
